package com.example.USD_WebServices;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.12.0
//
// Created by Quasar Development at 21/04/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RIPcreateTicketResponse extends AttributeContainer implements KvmSerializable
{

    
    public String createTicketReturn;
    
    public String newTicketHandle;
    
    public String newTicketNumber;
    
    public String returnUserData;
    
    public String returnApplicationData;

    public RIPcreateTicketResponse ()
    {
    }

    public RIPcreateTicketResponse (java.lang.Object paramObj,RIPExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("createTicketReturn"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.createTicketReturn = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.createTicketReturn = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("newTicketHandle"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.newTicketHandle = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.newTicketHandle = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("newTicketNumber"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.newTicketNumber = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.newTicketNumber = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("returnUserData"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.returnUserData = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.returnUserData = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("returnApplicationData"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.returnApplicationData = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.returnApplicationData = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return createTicketReturn;
        }
        if(propertyIndex==1)
        {
            return newTicketHandle;
        }
        if(propertyIndex==2)
        {
            return newTicketNumber;
        }
        if(propertyIndex==3)
        {
            return returnUserData;
        }
        if(propertyIndex==4)
        {
            return returnApplicationData;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "createTicketReturn";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "newTicketHandle";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "newTicketNumber";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "returnUserData";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "returnApplicationData";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
