package com.example.USD_WebServices;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.12.0
//
// Created by Quasar Development at 21/04/2016
//
//---------------------------------------------------



public interface RIPIServiceEvents
{
    public void Starting();
    public void Completed(RIPOperationResult result);
}
